# Usar una imagen base oficial de PHP con Apache
FROM php:8.0-apache

# Instalar git y unzip para el manejo de dependencias con Composer, además de librerías necesarias para algunas extensiones PHP
RUN apt-get update && apt-get install -y git unzip libpng-dev libonig-dev libxml2-dev

# Instalar extensiones de PHP que puedas necesitar
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Instalar Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Copiar los archivos de la aplicación al contenedor
COPY . /var/www/html

# Correr Composer para instalar dependencias
WORKDIR /var/www/html
RUN composer install --no-dev --optimize-autoloader

# Habilitar mod_rewrite y mod_headers para Apache (necesarios para Slim y manejo de cabeceras)
RUN a2enmod rewrite headers

# Corrección de permisos para el directorio web
RUN chown -R www-data:www-data /var/www/html

# Habilitar la visualización de errores de PHP para la depuración
# NOTA: Comentar o eliminar estas líneas en producción para seguridad
RUN echo 'php_flag display_startup_errors on' >> /var/www/html/.htaccess
RUN echo 'php_flag display_errors on' >> /var/www/html/.htaccess
RUN echo 'php_value error_reporting 32767' >> /var/www/html/.htaccess

# Configurar el registro de errores PHP
RUN echo 'php_flag log_errors on' >> /var/www/html/.htaccess
RUN echo 'php_value error_log /var/log/apache2/php_errors.log' >> /var/www/html/.htaccess

# Exponer el puerto 80 para acceder al contenedor
EXPOSE 80

# Configurar Apache para arrancar en modo foreground
CMD ["apache2-foreground"]


